### ISSUE TITLE
Adding correlationId

### ISSUE THREAD

**Issue by sydcanem** [mateodelnorte/servicebus#28]
Is there any way I could set a correlationId? In amqplib I can pass correlationId in options and get it as msg.properties.correlationId in .consume.

**Comment by mateodelnorte** [comment]
@sydcanem just a head's up: I've removed the properties middleware we created. instead, I'm exposing the original message envelope in addition to the message content. You can already set properties directly in the options parameter, so this streamlines things and no middleware are required. Here's what it looks like in use: 
```
bus.listen('routingKey', function (msg, envelope) {
   console.log(envelope.properties.correlationId);
});

bus.send('routingKey', { my: 'message' }, { correlationId: 'test-value' });
```
amqplib contains the logic to apply valid properties from the options object to the message envelope, so that's all transparent to us.

**Comment by tarunbatra** [comment]
I'm in a similar situation like @sydcanem. This discussion helped. Let's document this!
