### ISSUE TITLE
front end in mind

### ISSUE THREAD

**Issue by CodisRedding** [mateodelnorte/servicebus#80]
I'm on to the front end part of my poc for moving our arch to a service bus. You touched on UI interaction mongo oplog and the such, but I really don't understand how I'm going to handle our typical use cases like; form submissions that require a response before moving on to the next question (what if a service is down and the retry just sits on the queue, etc..), authentication where we don't let a portal user to send commands to the bus (via web app) until they receive a token, and all the other common scenarios with front end interaction. 

Do you have any examples and or insight on this? I'd love to chat with you about it more. ty (at the moment I'm exploring rethinkdb for the denormalizer)

**Comment by mateodelnorte** [comment]
You have two choices for form submissions. 

1) polling. create a reusable client side component that makes a POST to your application server. the app server fires off commands into your system. your client will then poll a GET looking for an expected value. if this value is unique to the user, perhaps the unique identifier is your users's userId in some collection, or a property being populated on their user object (or the user object itself). otherwise, you might create a unique id on the client, send that in on your POST and poll for it in some known location to get your resulting data. 
2) RPC. you generally wanna do this web websockets, though polling can work if it's abstrated (sockjs, etc). create a unique id on your client. make a post to your web app. your web app will create a unique correlationId and send a command to a downstream service. this upstream service will also subscribe for the event type which signifies the downstream service has completed its work. when that event (for instance, user.created) is received, your web app uses the correlationId to look up the correct web socket in table of Promises for web sockets who currently have RPC calls out and fulfills the promise with the data returned. You then send the data to the client and do as you wish. If you do this, you typically want to return data that is stored in a known location to be retrieved on first-load from some other flow. For instance, you'll return a user object via RPC to the client, but you'll still likely want the user object stored in a denormalizer table somewhere for ease load by other views, etc. 

In both scenarios the client needs timeouts to denote "Something went wrong. Please try again later.". You'll also want to think about how to communicate backend validation errors to the client. They'll follow the same flows as above. 

Mongo (via the oplog, like Meteor) and reThink both offer a slight variation on 1). There you don't have to poll, you can just rely on the data being pushed to you - unless you've timed out. 

So, in option 1) you're using the denormalizer and sticking with a unidirectional flow (all in the same direction). And in option 2) your system is still unidirectional, you just choose to make some flows go back to an originator in addition to flowing through to the denormalizer.

**Comment by CodisRedding** [comment]
Are there concerns about security with web sockets opposed to polling with typical http clients? From the get go I was leaning towards RPC, but the more I think about it, the more I realize I don't know the repercussions to using web sockets. The front end application for this company is pretty large, and we have to support quiet a wide variety of client devices. Polling seems to be the most straight forward easy to grasp concept . (though the term polling just seem shudder worthy in 2016). 

I would appreciate any more feed back about gothcya's to expect while converting an Angular (1.4 now, moving to 2) app to use polling in this service bus arch.

Thanks again!

**Comment by CodisRedding** [comment]
I'm checking out https://github.com/substack/dnode for RPC at the moment.

**Comment by eddieajau** [comment]
> Are there concerns about security with web sockets

No. The are actually more secure. At work we have completely replaced our traditional RESTful app with http://crossbar.io and haven't looked back.

But regarding your original question, why are you wanting to use the service bus for form handling (apart from final submission)? What's your workflow look like?

**Comment by mateodelnorte** [comment]
I've used dNode in the past. It's pretty fun to use dnode and sock in conjunction. Makes for a really cool client side experience. 

As for web sockets vs rpc, that's kind of mixing two decisions together which can really be done separately. 

1. How does the browser communicate with the web server (rest vs websockets)
2. How does the web server get an 'answer' from other services (rpc vs unidirectional flow through to denormalizer)

The flows you're describing span both. 

For 1, you can choose polling, forcing your clients to just do a refresh ("Check back in later for results or hit refresh!"), or you can give them realtime updates over websockets. sockjs and other libraries will auto-degrade from websockets to polling for you if you want the same behavior and don't want to choose. Part 1 is a piece of the _overall_ flow in that you'll create a unique id for your request (in the event you choose rpc for synchronous flows like auth). If you use REST, you'll post to the web server. If you're using websockets you'll send some data over the connection. You can even mix and match if you want to. 

For part 2, if you choose RPC your backend service will publish an event your web server listens to, which will cause it to then send a message back to your client. Decision 1 determines how it's sent back. For part 2, if you choose to have your data flow forward to your denormalizer, then your front web server will send some information back to your client denoting whether your denormalizerDb has been updated with some data in an expected place, denoting whether your flow has completed. 

Although the unidirectional flow is a less commonly found in the wild, my experience is that it's much easier to maintain and will lend you all sorts of levers for optimizing performance and adding new behavior.
