### ISSUE TITLE
Concerns about growth of denormalizer

### ISSUE THREAD

**Issue by CodisRedding** [mateodelnorte/servicebus#83]
I'm a little concerned about the denormalizer growing out of control and about the amount of domain logic the could potentially end up there while aggregating. As we decompose our some of our monoliths we will end up with a large amount of domain specific services that will eventually end up being aggregated in some way or another into the denormalizer service/db.

I think you mentioned that you've dealt with a large number of services and a single denormalizer before. Does it become hard to conceptualize over time, and how have you composed this service to help relieve that stress?

Isn't a "saga" a term used in CQRS as a way to have many denormalizers?

**Comment by mateodelnorte** [comment]
Here are a few points that will help:

1. Denormalizers should have no domain logic. All they does is save data
published by other services into a format used by your applications.
2. The best way to make sure the above is true is to always, only, do
upserts in your denormalizer.
3. You may have many handlers in your denormalizer. This is OK. Name them
according to the events being published in order to keep them easily
maintained. If a service published an event of type "order.canceled",
handle that in a handler named OrderCanceled.js. Only handle that one event
there.
4. Use servicebus-register-handlers to reduce subscribe overhead. If you
have multiple saves required for your apps to fully denormalize
"order.cancelled", having multiple handlers for that event won't cause
multiple subscriptions. It will subscribe once, loop through all handlers
upon event receipt, then ack when they all succeed.
5. Namespace your events according to the business domains they affect.
Have orders that are managed by an order service? "order.created",
"order.fulfilled", "order.cancelled" should all be event names. You can
imagine how these events may come from different handlers within an
order-svc and will be grouped near one another in a denormalizers
"handlers" folder.

Saga means "a multi step, multi service workflow". Sagas are workflows
managed by one service which keep state to represent steps having been
completed by downstream services in order to complete some local
processing. The denormalizer is still downstream of all of these services,
so it just subscribes to the same events (and more) which some upstream
service happens to subscribe to. The upstream service subscribers to them
because it needs to check correlation ids or some other data on the
messages to see if it's workflow is done. Denormalizers just want to
persist all event data to be viewable.

On Nov 10, 2016 7:41 PM, "Rocky Assad" <notifications@github.com> wrote:

I'm a little concerned about the denormalizer growing out of control and
about the amount of domain logic the could potentially end up there while
aggregating. As we decompose our some of our monoliths we will end up with
a large amount of domain specific services that will eventually end up
being aggregated in some way or another into the denormalizer service/db.

I think you mentioned that you've dealt with a large number of services and
a single denormalizer before. Does it become hard to conceptualize over
time, and how have you composed this service to help relieve that stress?

Isn't a "saga" a term used in CQRS as a way to have many denormalizers?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mateodelnorte/servicebus/issues/83>, or mute the thread

**Comment by mateodelnorte** [comment]
Since this is an architectural question, I'm going to go ahead and close the issue.

**Comment by CodisRedding** [comment]
thank you
